### PR TITLE
Specify Version for artifact - maven-assembly-plugin

### PR DESCRIPTION
**Pull request by ajinkyapatil8190**
This change will solve the day-2 operation run issue - https://github.com/SAP/fosstars-oss-rules-of-play-report/actions/runs/5651021176/job/15308385960#step:3:995

The job is not executing to create a jar file.

### CODE REVIEW

**Comment by sourabhsparkala** [comment]
@ajinkyapatil8190 there seems to be a error

image

**Comment by ajinkyapatil8190** [comment]
This test is failing for all the other PRs as well, not sure why this is caused, but I will look into it and hopefully solve it.

**Comment by ajinkyapatil8190** [comment]
This test is failing for all the other PRs as well, not sure why this is caused, nevertheless I will look into it.

**Comment by sourabhsparkala** [comment]
#963 updated maven-assembly-plugin here.

**Pull request closed without merging**
