### PR TITLE
Renamed SecurityLabel.OKAY to SecurityLabel.MODERATE

### LINKED ISSUE #56: Rename SecurityLabel.OKAY to SecurityLabel.MODERATE
The difference between GOOD and OKAY looks not that clear (in `com.sap.sgs.phosphor.fosstars.model.rating.oss.OssSecurityRating` the `SecurityLabel` enum).

I suggest to rename the `OKAY` to `MODERATE`. 
IMHO this fits better between `GOOD` and `BAD`.
Result would be:
```
public enum SecurityLabel implements Label {
  BAD, MODERATE, GOOD
}
```

See related PR #57 which I have created.

### PR DESCRIPTION
**Pull request by mibo**
Fixes #56

### CODE REVIEW

**Comment by mibo** [comment]
Rebased and changed commit message to follow CONTRIBUTING guidelines.

**Comment by artem-smotrakov** [comment]
Looks good to me.

**Comment by mibo** [comment]
> Thanks for addressing this @mibo . I was wondering if any docs need to be updated as well. Looks like the docs don't mention the old `OKAY` label. Only the README file contains a sample output from the demo tool which mentions the old label. I am going to update the sample output anyway, so no need to update the README now.

Perhaps in the future a section can be added describing the labels for the available ratings.
Or the enum itself could/should contain some JavaDoc or a description field. 
But both are out of scope for this PR  🙂

**Comment by artem-smotrakov** [comment]
@mibo Yes, the docs for the open-source security rating doesn't currently provide too much info. I agree that more details should be added. The javadoc would not make it worse either.

**Pull request merged**
